[package]
name = "everydice"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
miette = { version = "7.2.0", features = ["fancy"] }
thiserror = "1.0.63"
tree-sitter = "0.22"
tree-sitter-everydice = { path = "tree-sitter-everydice" }

[build-dependencies]
cc="*"
