// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_word = {__proto__:null,output:52, named:56, loop:62, over:64, if:72}
export const parser = LRParser.deserialize({
  version: 14,
  states: ")SOYQPOOOhQPO'#C`OOQO'#C_'#C_OOQO'#DR'#DRQYQPOOOmQPO'#CuO!UQPO'#CzOmQPO'#DPOmQPO,58zOOQO-E7P-E7POOQO'#Cd'#CdOmQPO'#DXOmQPO'#DXOOQO'#DX'#DXO!ZQQO'#DWOmQPO'#DWO$xQQO,59aO%cQPO,59fO%hQQO,59kO%oQQO1G.fOOQO,59s,59sO&VQQO,59sOmQPO,59sOmQPO,59sOmQPO,59sOmQPO,59sOmQPO,59sOmQPO,59sOmQPO,59sOOQO,59r,59rOmQPO,59rOmQPO,59rOmQPO,59rOmQPO,59rOmQPO,59rOmQPO,59rOmQPO,59rO&^QPO'#CwOOQO1G.{1G.{OmQPO1G/QOYQPO1G/VOOQO1G/_1G/_O'|QQO1G/_O(TQQO1G/_O)rQQO1G/_O)|QQO1G/_O+bQQO1G/_O+xQQO1G/_OOQO1G/^1G/^O-yQQO1G/^O.QQQO1G/^O/oQQO1G/^O/yQQO1G/^O1_QQO1G/^O1uQQO1G/^OOQO,59c,59cO2]QQO7+$lO2dQPO7+$qOYQPO<<HWOOQO<<H]<<H]O2uQPOAN=rOOQOG23^G23^",
  stateData: "3W~OxOSPOS~OjTOoUOtVOyPO~OTWO~OU[OX]OY_O`_OyYO|ZO}ZO~OyaO~OYfOZgO[hO]iO^iO_jO`jOakObkOckOdkOekOfkOglOhlOjzXlzXozXtzXvzXyzXqzXVzXrzX~OYnOZoO[pO]qO^qO_rO`rOasObsOcsOdsOesOfsOgtOhtO~OluOjiaoiatiaviayiaria~P#wOpwO~OqxO~P#wOjSioSitSivSiySirSi~P#wOVyO~P#wOm!XO~OYnO[{i]{i^{i_{i`{ia{ib{ic{id{ie{if{ig{ih{ij{il{io{it{iv{iy{iq{iV{ir{i~OZ{i~P&cOZoO~P&cOYnOZoO[pO_{i`{ia{ib{ic{id{ie{if{ig{ih{ij{il{io{it{iv{iy{iq{iV{ir{i~O]{i^{i~P([O]qO^qO~P([OYnOZoO[pO]qO^qO_rO`rOg{ih{ij{il{io{it{iv{iy{iq{iV{ir{i~Oa{ib{ic{id{ie{if{i~P*WOasObsOcsOdsOesOfsO~P*WOYnO[zi]zi^zi_zi`ziazibziczidziezifzigzihzijzilziozitzivziyziqziVzirzi~OZzi~P,`OZoO~P,`OYnOZoO[pO_zi`ziazibziczidziezifzigzihzijzilziozitzivziyziqziVzirzi~O]zi^zi~P.XO]qO^qO~P.XOYnOZoO[pO]qO^qO_rO`rOgzihzijzilziozitzivziyziqziVzirzi~Oazibziczidziezifzi~P0TOasObsOcsOdsOesOfsO~P0TOq![O~P#wOjTOoUOr!]OtVOyPO~OjTOoUOr!_OtVOyPO~O",
  goto: "%R|PPP}!VPPP!_PPPPPPPPPPPPPPPP!VP!vPP!VPPPP!VP!yPPPP#X$j]ROSx!Z![!^]QOSx!Z![!^{]TVWZ[_fghijklnopqrstwRv`QSOUXS!Z!^Q!ZxR!^![Q`TQbVQcWQdZQe[Qm_QyfQzgQ{hQ|iQ}jQ!OkQ!PlQ!QnQ!RoQ!SpQ!TqQ!UrQ!VsQ!WtR!Yw{^TVWZ[_fghijklnopqrstw",
  nodeNames: "⚠ Comment Program Statement Assignment : ( ) Reference Number d @ ^ * / + - = != < <= > >= & | Output output OutputName named String LoopStatement loop over { } IfStatement if",
  maxTerm: 46,
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: "+u~RpX^#Vpq#Vqr#zrs$Xst%uvw%zxy&Pyz&Uz{&Z{|&`}!O&e!P!Q&j![!]&o!^!_&t!_!`'R!`!a'W!b!c'e!}#O'j#O#P*m#Q#R+[#W#X+a#o#p+f#p#q+k#q#r+p#y#z#V$f$g#V#BY#BZ#V$IS$I_#V$I|$JO#V$JT$JU#V$KV$KW#V&FU&FV#V~#[Yx~X^#Vpq#V#y#z#V$f$g#V#BY#BZ#V$IS$I_#V$I|$JO#V$JT$JU#V$KV$KW#V&FU&FV#VR$PP}P!_!`$SQ$XObQ~$[VOr$Xrs$qs#O$X#O#P$v#P;'S$X;'S;=`%o<%lO$X~$vOm~~$yRO;'S$X;'S;=`%S;=`O$X~%VWOr$Xrs$qs#O$X#O#P$v#P;'S$X;'S;=`%o;=`<%l$X<%lO$X~%rP;=`<%l$X~%zO|~~&POg~~&UOU~~&ZOV~~&`O]~~&eO_~~&jO`~~&oO^~~&tOT~~&yPc~!_!`&|~'ROd~~'WOa~~']Pe~!_!`'`~'eOf~~'jOZ~~'mR!Q!R'v!c!d(e#T#U)Y~'yP}!O'|~(PP!Z![(S~(VP#P#Q(Y~(]P{|(`~(eOX~~(hP}!O(k~(nP!|!}(q~(tP#R#S(w~(zP#P#Q(}~)QP{|)T~)YOy~~)]P}!O)`~)cP#n#o)f~)iP#P#Q)l~)oP!}#O)r~)uP#T#U)x~){P}!O*O~*RP#n#o*U~*XP#R#S*[~*_P#P#Q*b~*eP{|*h~*mO!O~~*pTO#O*m#O#P+P#P;'S*m;'S;=`+U<%lO*m~+UOP~~+XP;=`<%l*m~+aO[~~+fOY~~+kOq~~+pOh~~+uOr~",
  tokenizers: [0, 1],
  topRules: {"Program":[0,2]},
  specialized: [{term: 46, get: (value: keyof typeof spec_word) => spec_word[value] || -1}],
  tokenPrec: 0
})
