// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  Program = 2,
  Statement = 3,
  Assignment = 4,
  Reference = 8,
  Number = 9,
  Output = 25,
  output = 26,
  OutputName = 27,
  named = 28,
  String = 29,
  LoopStatement = 30,
  loop = 31,
  over = 32,
  IfStatement = 35,
  _if = 36
